# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

# The entry name that will be displayed in the boot menu.
/PrometheOS
PROTOCOL: multiboot2
KERNEL_PATH: boot():/boot/prometheos.kernel
MODULE_PATH: boot():/boot/prometheos.initrd