import argparse
ISRS_WITH_ERROR_CODE = [8,10,11,12,13,14,17,21,29,30]
parser = argparse.ArgumentParser("generate_isrs.py")
parser.add_argument("cfile")
parser.add_argument("asmfile")
args = parser.parse_args()
print(args.cfile)

CFILE   = open(args.cfile,"w")
ASMFILE = open(args.asmfile,"w")

for i in range(256):
    if i in ISRS_WITH_ERROR_CODE:
        ASMFILE.write(f"ISR_ERRORCODE {i}\n")
    else:
        ASMFILE.write(f"ISR_NOERRORCODE {i}\n")

#setIDTGate(0, ISR0, GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);

CFILE.write("// !!! AUTOGENERATED FILE !!!\n")
CFILE.write("#include <kernel/idt.h>\n")
CFILE.write("#include <kernel/gdt.h>\n")
CFILE.write("\n")
for i in range(256):
    CFILE.write(f"void __attribute__((cdecl)) ISR{i}();\n")
CFILE.write("\n")
CFILE.write("void ISR_InitializeGates() {\n")
for i in range(256):
    CFILE.write(f"    setIDTGate({i}, ISR{i}, GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);\n")

CFILE.write("}")

CFILE.close()
ASMFILE.close()